name: CI

on:
  pull_request:
    paths:
      - '**.ts'
      - '**eslint**'
      - 'package-lock.json'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    name: Lint
    env:
      CI: true
      HUSKY_SKIP_INSTALL: true
      FORCE_COLOR: 2

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install Packages
        run: npm ci

      - name: Lint
        run: npm run -s lint

      - name: Typecheck
        run: npx tsc --noEmit
